name: Build Docker Image and Push to Container Registry.

on:
  push:
    branch:
      -main
      
env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  IMAGE: github-action-cloud-scheduler
  TAG: 1.0.0
  
jobs:
  setup-build-publish-deploy:
    name: Build Docker Image and Push to Container Registry.
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout Repository 
        uses: actions/checkout@v2
      
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          settings-path: ${{github.workspace}}
          
      - name: Build with Gradle
        run:  gradle build -x test 
        
      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}
          
      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
          
      - name: Build Docker Image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .
          
      - name: Publish Docker Image
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"
